# Generated by Django 3.0.4 on 2022-07-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shop_name', models.CharField(max_length=100)),
                ('menu_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=100)),
            ],
        ),
    ]
