# Generated by Django 3.0.4 on 2022-07-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lunchrec', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyList',
            new_name='LunchrecList',
        ),
    ]
