# Generated by Django 3.0.4 on 2022-07-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauna', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sauna',
            name='holiday',
            field=models.CharField(max_length=10),
        ),
    ]
