# Generated by Django 3.0.4 on 2022-07-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=30)),
                ('jenre', models.CharField(max_length=30)),
                ('holiday', models.CharField(max_length=30)),
                ('wifi', models.BooleanField()),
                ('url', models.URLField()),
                ('mail', models.EmailField(max_length=50)),
                ('registdate', models.DateField()),
            ],
        ),
    ]
