# Generated by Django 3.0.4 on 2022-07-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyList',
            new_name='Gourmet',
        ),
    ]
