# Generated by Django 3.0.4 on 2022-07-07 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0002_auto_20220707_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gourmet',
            old_name='jenre',
            new_name='genre',
        ),
    ]
