# Generated by Django 3.0.4 on 2022-07-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0003_auto_20220707_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gourmet',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='gourmet',
            name='registdate',
        ),
        migrations.RemoveField(
            model_name='gourmet',
            name='url',
        ),
        migrations.AddField(
            model_name='gourmet',
            name='coupon_urls',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gourmet',
            name='non_smoking',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='gourmet',
            name='urls',
            field=models.URLField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gourmet',
            name='holiday',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='gourmet',
            name='wifi',
            field=models.BooleanField(null=True),
        ),
    ]
