# Generated by Django 3.0.4 on 2022-07-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gourmet', '0005_auto_20220708_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='gourmet',
            name='shop_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
