# Generated by Django 3.0.4 on 2022-07-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QiitaSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=100, null=True)),
                ('created_at', models.CharField(max_length=30)),
                ('updated_at', models.CharField(max_length=30)),
                ('comments_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('reactions_count', models.IntegerField(default=0)),
            ],
        ),
    ]
